### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by TDR-1000** [KhanhNguyen9872/hyperion_deobfuscate#1]
Virus?

**Comment by KhanhNguyen9872** [comment]
> Virus?

this file was pack by pyinstaller, then it look like a virus if you scan it! but the file don't have any virus bro:)) and i don't share source code

**Comment by KhanhNguyen9872** [comment]
> Virus?

you can test it in virtual machine if you want! again, it not a virus

**Comment by Mr-Bitch** [comment]
@TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000 @TDR-1000
