### ISSUE TITLE
1

### ISSUE THREAD

**Issue by dasfasdfasdfsdf** [KhanhNguyen9872/hyperion_deobfuscate#3]
1

**Comment by KhanhNguyen9872** [comment]
> File "", line 13, in File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\logging__init__.py", line 26, in import sys, os, time, io, re, traceback, warnings, weakref, collections.abc ModuleNotFoundError: import of sys halted; None in sys.modules AttributeError: 'NoneType' object has no attribute '_shutdown'

don't worry about that, you can ignore this error if deobf completed

**Comment by KhanhNguyen9872** [comment]
> File "", line 13, in File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\logging__init__.py", line 26, in import sys, os, time, io, re, traceback, warnings, weakref, collections.abc ModuleNotFoundError: import of sys halted; None in sys.modules AttributeError: 'NoneType' object has no attribute '_shutdown'

because sys library has modified when deobf hyperion, then logging library cannot exit completely (sys -> None)

**Comment by life-live** [comment]
> > File "", line 13, in File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\logging__init__.py", line 26, in import sys, os, time, io, re, traceback, warnings, weakref, collections.abc ModuleNotFoundError: import of sys halted; None in sys.modules AttributeError: 'NoneType' object has no attribute '_shutdown'
> 
> don't worry about that, you can ignore this error if deobf completed

My deobfuscation was unsuccessful, the file did not appear

![image](https://github.com/KhanhNguyen9872/hyperion_deobfuscate/assets/96289868/72009243-5578-4b14-9117-e379580fe737)

![image](https://github.com/KhanhNguyen9872/hyperion_deobfuscate/assets/96289868/4990faeb-5510-4872-b88e-62bba281a99f)

Here is the code I want to deobfuscate. 
**THIS IS A VIRUS, DO NOT RUN IT ON THE MAIN MACHINE AND WORK WITH THIS FILE CAREFULLY!**
https://paste.website/p/0daa57ce-4f5c-495e-b25c-27068b57e125.txt
**THIS IS A VIRUS, DO NOT RUN IT ON THE MAIN MACHINE AND WORK WITH THIS FILE CAREFULLY!**

**Comment by KhanhNguyen9872** [comment]
> 

## thanks for your file! here is a source code
[ket_qua_cua_viec_dep_trai_deobf_layer_84_main.txt](https://github.com/KhanhNguyen9872/hyperion_deobfuscate/files/12484304/ket_qua_cua_viec_dep_trai_deobf_layer_84_main.txt)

## Here is video how to deobf if auto_mode cannot done: [here](https://github.com/KhanhNguyen9872/PublicFile/releases/download/tempfiles/2023-08-31.15-43-59.mkv)

WARNING: you are right when deobf on virtual machine, fortunately this file after obf failed to run, so i recommend you to use virtual machine

**Comment by KhanhNguyen9872** [comment]
If you have nothing more to ask, I'll close the issue in a few hours

**Comment by KhanhNguyen9872** [comment]
> 



> File "", line 13, in File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python310\lib\logging__init__.py", line 26, in import sys, os, time, io, re, traceback, warnings, weakref, collections.abc ModuleNotFoundError: import of sys halted; None in sys.modules AttributeError: 'NoneType' object has no attribute '_shutdown'

Maybe you won't get notification after I comment so I'll reply you one more time

**Comment by life-live** [comment]
Thanks for help

**Comment by KhanhNguyen9872** [comment]
> Thanks for help

Thank you for using my program!
