### ISSUE TITLE
NameError: name 'bbllaacckk_KhanhNguyen9872' is not defined

### ISSUE THREAD

**Issue by termuxsploit** [KhanhNguyen9872/hyperion_deobfuscate#4]
### Excellent work
But i have error when trying hyperion deobfuscate on ****Termux Android**** with ****Python 3.11****.

ERROR
```text
/sdcard/hyperion_deobfuscate $ python3.11 hyperion-deobf_py311.py
>>> Hyperion Deobf by KhanhNguyen9872
>>> FB: https://fb.me/khanh10a1                                       
!! ĐÂY LÀ TOOL SHARE FREE TẠI GITHUB KHANHNGUYEN9872 !!
!! NẾU BẠN MUA TOOL NÀY TỪ MỘT AI ĐÓ, HỌ LÀ LỪA ĐẢO !!

>> Python: 3.11
!! auto detect code+vars? [Y/n]: n
!! Do you want to deobf all first layer? [Y/n]: y
<< Input full file Hyperion: enc.py
>> reading file....
>> please wait.....
    module __main__ raised an Exception:
     name 'bbllaacckk_KhanhNguyen9872' is not defined
Traceback (most recent call last):
  File "<KhanhNguyen9872>", line 30, in decompress
NameError: name 'bbllaacckk_KhanhNguyen9872' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<KhanhNguyen9872>", line 632, in <module>
  File "<KhanhNguyen9872>", line 628, in <lambda>
  File "<KhanhNguyen9872>", line 32, in decompress
NameError: name 'bbllaacckk_KhanhNguyen9872' is not defined

>> Done all first layer!
/sdcard/hyperion_deobfuscate $ ls
README.md  hyperion-deobf_py310.py  hyperion-deobf_py39.py
enc.py     hyperion-deobf_py311.py  temp_code.py
enc_py     hyperion-deobf_py38.py
/sdcard/hyperion_deobfuscate $ cat enc_py/deobf_layer_0_enc.txt
/sdcard/hyperion_deobfuscate $
```
I have tried with Python 3.8 version and the results still give the same error

This is the obfuscated code:
****https://filebin.net/1s54yq2qvcgptbgn/enc.py****

**Comment by KhanhNguyen9872** [comment]
> ### Excellent work
> But i have error when trying hyperion deobfuscate on **Termux Android** with **Python 3.11**.
> 
> ERROR
> 
> ```
> /sdcard/hyperion_deobfuscate $ python3.11 hyperion-deobf_py311.py
> >>> Hyperion Deobf by KhanhNguyen9872
> >>> FB: https://fb.me/khanh10a1                                       
> !! ĐÂY LÀ TOOL SHARE FREE TẠI GITHUB KHANHNGUYEN9872 !!
> !! NẾU BẠN MUA TOOL NÀY TỪ MỘT AI ĐÓ, HỌ LÀ LỪA ĐẢO !!
> 
> >> Python: 3.11
> !! auto detect code+vars? [Y/n]: n
> !! Do you want to deobf all first layer? [Y/n]: y
> << Input full file Hyperion: enc.py
> >> reading file....
> >> please wait.....
>     module __main__ raised an Exception:
>      name 'bbllaacckk_KhanhNguyen9872' is not defined
> Traceback (most recent call last):
>   File "<KhanhNguyen9872>", line 30, in decompress
> NameError: name 'bbllaacckk_KhanhNguyen9872' is not defined
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<KhanhNguyen9872>", line 632, in <module>
>   File "<KhanhNguyen9872>", line 628, in <lambda>
>   File "<KhanhNguyen9872>", line 32, in decompress
> NameError: name 'bbllaacckk_KhanhNguyen9872' is not defined
> 
> >> Done all first layer!
> /sdcard/hyperion_deobfuscate $ ls
> README.md  hyperion-deobf_py310.py  hyperion-deobf_py39.py
> enc.py     hyperion-deobf_py311.py  temp_code.py
> enc_py     hyperion-deobf_py38.py
> /sdcard/hyperion_deobfuscate $ cat enc_py/deobf_layer_0_enc.txt
> /sdcard/hyperion_deobfuscate $
> ```
> 
> I have tried with Python 3.8 version and the results still give the same error
> 
> This is the obfuscated code: **https://filebin.net/1s54yq2qvcgptbgn/enc.py**

![image](https://github.com/KhanhNguyen9872/hyperion_deobfuscate/assets/88880309/fab31321-6709-4a3f-8594-de89e85d4293)

# Thanks for your bug report! I fixed it! You can test again!
try use [auto detect code+vars] [Y]
here is your deobf enc.py [ket_qua_cua_viec_dep_trai_enc.txt](https://github.com/KhanhNguyen9872/hyperion_deobfuscate/files/12749932/ket_qua_cua_viec_dep_trai_enc.txt) (Fast mode)

**Comment by termuxsploit** [comment]
Thanks for reply, it work perfectly. 🔥
****SOLVED****
